spring:
  application:
    name: work-attendance-service

service:
  instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: 0 # random port

kafka:
  topicName: work-attendance-events

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env,caches,threaddump,logfile"

security:
  service:
    username: microservice
    password: password

eureka:
  instance:
    instanceId: ${service.instanceId}
  client:
    serviceUrl:
      defaultZone: http://${security.service.username}:${security.service.password}@localhost:8761/eureka/

services:
  employeeServiceName: employee-service

springdoc:
  swagger-ui:
    path: /work-attendances/swagger-ui.html
  api-docs:
    path: /work-attendances/api-docs

#logging:
#  file:
#    name: ./logs/${spring.application.name}-log.log
