spring:
  application:
    name: work-attendance-service

service:
  instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: 0 # random port

kafka:
  topicName: work-attendance-events

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env,caches,threaddump,logfile"

eureka:
  instance:
    instanceId: ${service.instanceId}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

services:
  employeeServiceName: employee-service

#logging:
#  file:
#    name: ./logs/${spring.application.name}-log.log
