spring:
  application:
    name: work-attendance-service

service:
  instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: 0 # random port

kafka:
  bootstrapServers: ${KAFKA_BOOTSTRAP_SERVERS}
  topicName: work-attendance-events

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env,caches,threaddump,logfile,prometheus"

security:
  username: ${EUREKA_SECURITY_USERNAME}
  password: ${EUREKA_SECURITY_PASSWORD}

eureka:
  instance:
    instanceId: ${service.instanceId}
  client:
    serviceUrl:
      defaultZone: http://${security.username}:${security.password}@${EUREKA_SERVER_HOST}:8761/eureka/

services:
  employeeServiceName: employee-service

springdoc:
  swagger-ui:
    path: /work-attendances/swagger-ui.html
  api-docs:
    path: /work-attendances/api-docs

logging:
  file:
    name: ./logs/${spring.application.name}-log.log
