spring:
  application:
    name: work-attendance-service

service:
  instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: ${SERVER_PORT}

kafka:
  bootstrapServers: ${KAFKA_BOOTSTRAP_SERVERS}
  topicName: work-attendance-events
  sasl:
    username: ${KAFKA_SASL_USERNAME}
    password: ${KAFKA_SASL_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env,caches,threaddump,logfile,prometheus"

eureka:
  client:
    enabled: false

services:
  employeeService:
    name: employee-service
    url: ${EMPLOYEE_SERVICE_URL}

springdoc:
  swagger-ui:
    path: /work-attendances/swagger-ui.html
  api-docs:
    path: /work-attendances/api-docs

logging:
  file:
    name: ./logs/${spring.application.name}-log.log
