name: 'payroll-system'

services:
  keycloak-db:
    image: postgres:17.0
    environment:
      - POSTGRES_DB=${KEYCLOAK_DB}
      - POSTGRES_USER=${KEYCLOAK_DB_USERNAME}
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
    volumes:
      - keycloak-db:/var/lib/postgresql/data

  keycloak:
    image: gabrielluciano/ps-keycloak:1.0
    ports:
      - "8443:8443"
      - "9000:9000"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KC_ADMIN_USERNAME}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_ADMIN_PASSWORD}
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/${KEYCLOAK_DB}
      - KC_DB_USERNAME=${KEYCLOAK_DB_USERNAME}
      - KC_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
    command: start --optimized
    depends_on:
      - keycloak-db

  discovery-server:
    image: gabrielluciano/ps-discovery-server:1.0
    ports:
      - "8761:8761"
    environment:
      - EUREKA_SECURITY_USERNAME=${EUREKA_SECURITY_USERNAME}
      - EUREKA_SECURITY_PASSWORD=${EUREKA_SECURITY_PASSWORD}

  employee-service-db:
    image: postgres:17.0
    environment:
      - POSTGRES_DB=${EMPLOYEE_SERVICE_DATABASE_NAME}
      - POSTGRES_USER=${EMPLOYEE_SERVICE_DATABASE_USER}
      - POSTGRES_PASSWORD=${EMPLOYEE_SERVICE_DATABASE_PASSWORD}
    volumes:
      - ./employee-service/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - employee-service-db:/var/lib/postgresql/data

  employee-service:
    image: gabrielluciano/ps-employee-service:1.0
    environment:
      - DATABASE_URL=jdbc:postgresql://employee-service-db:5432
      - DATABASE_NAME=${EMPLOYEE_SERVICE_DATABASE_NAME}
      - DATABASE_USER=${EMPLOYEE_SERVICE_DATABASE_USER}
      - DATABASE_PASSWORD=${EMPLOYEE_SERVICE_DATABASE_PASSWORD}
      - EUREKA_SECURITY_USERNAME=${EUREKA_SECURITY_USERNAME}
      - EUREKA_SECURITY_PASSWORD=${EUREKA_SECURITY_PASSWORD}
      - EUREKA_SERVER_HOST=discovery-server
    depends_on:
      - employee-service-db
      - discovery-server

  inss-tax-service-db:
    image: postgres:17.0
    environment:
      - POSTGRES_DB=${INSS_TAX_SERVICE_DATABASE_NAME}
      - POSTGRES_USER=${INSS_TAX_SERVICE_DATABASE_USER}
      - POSTGRES_PASSWORD=${INSS_TAX_SERVICE_DATABASE_PASSWORD}
    volumes:
      - ./inss-tax-service/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - inss-tax-service-db:/var/lib/postgresql/data

  inss-tax-service:
    image: gabrielluciano/ps-inss-tax-service:1.0
    environment:
      - DATABASE_URL=jdbc:postgresql://inss-tax-service-db:5432
      - DATABASE_NAME=${INSS_TAX_SERVICE_DATABASE_NAME}
      - DATABASE_USER=${INSS_TAX_SERVICE_DATABASE_USER}
      - DATABASE_PASSWORD=${INSS_TAX_SERVICE_DATABASE_PASSWORD}
      - EUREKA_SECURITY_USERNAME=${EUREKA_SECURITY_USERNAME}
      - EUREKA_SECURITY_PASSWORD=${EUREKA_SECURITY_PASSWORD}
      - EUREKA_SERVER_HOST=discovery-server
    depends_on:
      - inss-tax-service-db
      - discovery-server

  income-tax-service-db:
    image: postgres:17.0
    environment:
      - POSTGRES_DB=${INCOME_TAX_SERVICE_DATABASE_NAME}
      - POSTGRES_USER=${INCOME_TAX_SERVICE_DATABASE_USER}
      - POSTGRES_PASSWORD=${INCOME_TAX_SERVICE_DATABASE_PASSWORD}
    volumes:
      - ./income-tax-service/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - income-tax-service-db:/var/lib/postgresql/data

  income-tax-service:
    image: gabrielluciano/ps-income-tax-service:1.0
    environment:
      - DATABASE_URL=jdbc:postgresql://income-tax-service-db:5432
      - DATABASE_NAME=${INCOME_TAX_SERVICE_DATABASE_NAME}
      - DATABASE_USER=${INCOME_TAX_SERVICE_DATABASE_USER}
      - DATABASE_PASSWORD=${INCOME_TAX_SERVICE_DATABASE_PASSWORD}
      - EUREKA_SECURITY_USERNAME=${EUREKA_SECURITY_USERNAME}
      - EUREKA_SECURITY_PASSWORD=${EUREKA_SECURITY_PASSWORD}
      - EUREKA_SERVER_HOST=discovery-server
    depends_on:
      - income-tax-service-db
      - discovery-server

  kafka-controller-1:
    image: apache/kafka:3.8.0
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9093,3@kafka-controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - kafka-controller-1-secrets:/etc/kafka/secrets
      - kafka-controller-1-data:/var/lib/kafka/data
      - kafka-controller-1-config:/mnt/shared/config

  kafka-controller-2:
    image: apache/kafka:3.8.0
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9093,3@kafka-controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - kafka-controller-2-secrets:/etc/kafka/secrets
      - kafka-controller-2-data:/var/lib/kafka/data
      - kafka-controller-2-config:/mnt/shared/config

  kafka-controller-3:
    image: apache/kafka:3.8.0
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9093,3@kafka-controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - kafka-controller-3-secrets:/etc/kafka/secrets
      - kafka-controller-3-data:/var/lib/kafka/data
      - kafka-controller-3-config:/mnt/shared/config

  kafka-broker-1:
    image: apache/kafka:3.8.0
    ports:
      - 29092:9092
    environment:
      KAFKA_NODE_ID: 4
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-broker-1:19092,PLAINTEXT_HOST://localhost:29092'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9093,3@kafka-controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - kafka-broker-1-secrets:/etc/kafka/secrets
      - kafka-broker-1-data:/var/lib/kafka/data
      - kafka-broker-1-config:/mnt/shared/config
    depends_on:
      - kafka-controller-1
      - kafka-controller-2
      - kafka-controller-3

  kafka-broker-2:
    image: apache/kafka:3.8.0
    ports:
      - 39092:9092
    environment:
      KAFKA_NODE_ID: 5
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-broker-2:19092,PLAINTEXT_HOST://localhost:39092'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9093,3@kafka-controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - kafka-broker-2-secrets:/etc/kafka/secrets
      - kafka-broker-2-data:/var/lib/kafka/data
      - kafka-broker-2-config:/mnt/shared/config
    depends_on:
      - kafka-controller-1
      - kafka-controller-2
      - kafka-controller-3

  kafka-broker-3:
    image: apache/kafka:3.8.0
    ports:
      - 49092:9092
    environment:
      KAFKA_NODE_ID: 6
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-broker-3:19092,PLAINTEXT_HOST://localhost:49092'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9093,3@kafka-controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - kafka-broker-3-secrets:/etc/kafka/secrets
      - kafka-broker-3-data:/var/lib/kafka/data
      - kafka-broker-3-config:/mnt/shared/config
    depends_on:
      - kafka-controller-1
      - kafka-controller-2
      - kafka-controller-3

  work-attendance-service:
    image: gabrielluciano/ps-work-attendance-service:1.0
    environment:
      - EUREKA_SECURITY_USERNAME=${EUREKA_SECURITY_USERNAME}
      - EUREKA_SECURITY_PASSWORD=${EUREKA_SECURITY_PASSWORD}
      - EUREKA_SERVER_HOST=discovery-server
      - KAFKA_BOOTSTRAP_SERVERS=kafka-broker-1:19092,kafka-broker-2:19092,kafka-broker-3:19092
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
      - discovery-server

  payroll-service-db:
    image: postgres:17.0
    environment:
      - POSTGRES_DB=${PAYROLL_SERVICE_DATABASE_NAME}
      - POSTGRES_USER=${PAYROLL_SERVICE_DATABASE_USER}
      - POSTGRES_PASSWORD=${PAYROLL_SERVICE_DATABASE_PASSWORD}
    volumes:
      - ./payroll-service/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - payroll-service-db:/var/lib/postgresql/data

  payroll-service:
    image: gabrielluciano/ps-payroll-service:1.0
    environment:
      - DATABASE_URL=jdbc:postgresql://payroll-service-db:5432
      - DATABASE_NAME=${PAYROLL_SERVICE_DATABASE_NAME}
      - DATABASE_USER=${PAYROLL_SERVICE_DATABASE_USER}
      - DATABASE_PASSWORD=${PAYROLL_SERVICE_DATABASE_PASSWORD}
      - EUREKA_SECURITY_USERNAME=${EUREKA_SECURITY_USERNAME}
      - EUREKA_SECURITY_PASSWORD=${EUREKA_SECURITY_PASSWORD}
      - EUREKA_SERVER_HOST=discovery-server
      - KAFKA_BOOTSTRAP_SERVERS=kafka-broker-1:19092,kafka-broker-2:19092,kafka-broker-3:19092
    depends_on:
      - payroll-service-db
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
      - discovery-server

  api-gateway:
    image: gabrielluciano/ps-api-gateway:1.0
    environment:
      - EUREKA_SECURITY_USERNAME=${EUREKA_SECURITY_USERNAME}
      - EUREKA_SECURITY_PASSWORD=${EUREKA_SECURITY_PASSWORD}
      - EUREKA_SERVER_HOST=discovery-server
      - AUTHZ_SERVER_ISSUER_URI=https://keycloak:8443/realms/payroll-system
      - AUTHZ_SERVER_JWK_SET_URI=https://keycloak:8443/realms/payroll-system/protocol/openid-connect/certs
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
      - keycloak
      - employee-service
      - income-tax-service
      - inss-tax-service
      - work-attendance-service
      - payroll-service

volumes:
  keycloak-db:
  employee-service-db:
  inss-tax-service-db:
  income-tax-service-db:
  payroll-service-db:
  kafka-controller-1-secrets:
  kafka-controller-1-data:
  kafka-controller-1-config:
  kafka-controller-2-secrets:
  kafka-controller-2-data:
  kafka-controller-2-config:
  kafka-controller-3-secrets:
  kafka-controller-3-data:
  kafka-controller-3-config:
  kafka-broker-1-secrets:
  kafka-broker-1-data:
  kafka-broker-1-config:
  kafka-broker-2-secrets:
  kafka-broker-2-data:
  kafka-broker-2-config:
  kafka-broker-3-secrets:
  kafka-broker-3-data:
  kafka-broker-3-config:


