spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTHZ_SERVER_ISSUER_URI}
          jwk-set-uri: ${AUTHZ_SERVER_JWK_SET_URI}

service:
  instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env,caches,threaddump,logfile,prometheus"

security:
  username: ${EUREKA_SECURITY_USERNAME}
  password: ${EUREKA_SECURITY_PASSWORD}

eureka:
  instance:
    instanceId: ${service.instanceId}
  client:
    serviceUrl:
      defaultZone: http://${security.username}:${security.password}@${EUREKA_SERVER_HOST}:8761/eureka/

logging:
  file:
    name: ./logs/${spring.application.name}-log.log
