spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000/realms/payroll-system

server:
  port: 8080

service:
  instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env,caches,threaddump,logfile,prometheus"

security:
  username: microservice
  password: password

services:
  employeeService:
    name: employee-service
    url: lb://employee-service
  incomeTaxService:
    name: income-tax-service
    url: lb://income-tax-service
  inssTaxService:
    name: inss-tax-service
    url: lb://inss-tax-service
  workAttendanceService:
    name: work-attendance-service
    url: lb://work-attendance-service
  payrollService:
    name: payroll-service
    url: lb://payroll-service

eureka:
  instance:
    instanceId: ${service.instanceId}
  client:
    serviceUrl:
      defaultZone: http://${security.username}:${security.password}@localhost:8761/eureka/

#logging:
#  file:
#    name: ./logs/${spring.application.name}-log.log
