spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTHZ_SERVER_ISSUER_URI}
          jwk-set-uri: ${AUTHZ_SERVER_JWK_SET_URI}

server:
  port: ${SERVER_PORT}

service:
  instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env,caches,threaddump,logfile,prometheus"

security:
  username: ${METRICS_SECURITY_USERNAME}
  password: ${METRICS_SECURITY_PASSWORD}

services:
  employeeService:
    name: employee-service
    url: ${EMPLOYEE_SERVICE_URL}
  incomeTaxService:
    name: income-tax-service
    url: ${INCOME_TAX_SERVICE_URL}
  inssTaxService:
    name: inss-tax-service
    url: ${INSS_TAX_SERVICE_URL}
  workAttendanceService:
    name: work-attendance-service
    url: ${WORK_ATTENDANCE_SERVICE_URL}
  payrollService:
    name: payroll-service
    url: ${PAYROLL_SERVICE_URL}

eureka:
  client:
    enabled: false

logging:
  file:
    name: ./logs/${spring.application.name}-log.log
