spring:
  application:
    name: employee-service
  datasource:
    url: ${DATABASE_URL}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env,caches,threaddump,logfile,prometheus"

security:
  username: ${EUREKA_SECURITY_USERNAME}
  password: ${EUREKA_SECURITY_PASSWORD}

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://${security.username}:${security.password}@${EUREKA_SERVER_HOST}:8761/eureka/

springdoc:
  swagger-ui:
    path: /employees/swagger-ui.html
  api-docs:
    path: /employees/api-docs

logging:
  file:
    name: ./logs/${spring.application.name}-log.log
