spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_db
    username: service
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
