spring:
  application:
    name: discovery-server

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env,caches,threaddump,logfile,prometheus"

security:
  username: ${EUREKA_SECURITY_USERNAME}
  password: ${EUREKA_SECURITY_PASSWORD}

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${security.username}:${security.password}@${eureka.instance.hostname}:${server.port}/eureka/

logging:
  file:
    name: ./logs/${spring.application.name}-log.log
