spring:
  application:
    name: discovery-server

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env,caches,threaddump,logfile"

security:
  user:
    username: admin
    password: password
  service:
    username: microservice
    password: password

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${security.service.username}:${security.service.password}@${eureka.instance.hostname}:${server.port}/eureka/

