spring:
  application:
    name: inss-tax-service
  datasource:
    url: ${DATABASE_URL}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none

service:
  instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: ${SERVER_PORT}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env,caches,threaddump,logfile,prometheus"

eureka:
  client:
    enabled: false

springdoc:
  swagger-ui:
    path: /inss/swagger-ui.html
  api-docs:
    path: /inss/api-docs

logging:
  file:
    name: ./logs/${spring.application.name}-log.log
