apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: api-gateway
          image: localhost:32000/ps-k8s-api-gateway:1.0
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: METRICS_SECURITY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: metrics-security
                  key: username
            - name: METRICS_SECURITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: metrics-security
                  key: password

            - name: AUTHZ_SERVER_ISSUER_URI
              value: http://keycloak/realms/payroll-system
            - name: AUTHZ_SERVER_JWK_SET_URI
              value: http://keycloak/realms/payroll-system/protocol/openid-connect/certs

            - name: EMPLOYEE_SERVICE_URL
              value: http://employee-service:8080
            - name: INCOME_TAX_SERVICE_URL
              value: http://income-tax-service:8080
            - name: INSS_TAX_SERVICE_URL
              value: http://inss-tax-service:8080
            - name: WORK_ATTENDANCE_SERVICE_URL
              value: http://work-attendance-service:8080
            - name: PAYROLL_SERVICE_URL
              value: http://payroll-service:8080
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
