apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9000"
    spec:
      containers:
        - name: keycloak
          image: localhost:32000/ps-k8s-keycloak:1.0
          args: ["start", "--optimized", "--hostname-strict", "false", "--http-enabled", "true"]
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin
                  key: user
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin
                  key: password
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-db
                  key: user
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db
                  key: password
            - name: KC_DB_URL
              value: "jdbc:postgresql://keycloak-db:5432/keycloak_db"
            - name: KC_HOSTNAME
              value: keycloak
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
