services:
  db:
    image: postgres:17.0
    environment:
      - POSTGRES_DB=${KEYCLOAK_DB}
      - POSTGRES_USER=${KEYCLOAK_DB_USERNAME}
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
    volumes:
      - payroll-keycloak:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.2
    ports:
      - "8000:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KC_ADMIN_USERNAME}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/${KEYCLOAK_DB}
      - KC_DB_USERNAME=${KEYCLOAK_DB_USERNAME}
      - KC_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - KC_HOSTNAME=localhost
    command: start-dev
    depends_on:
      - db

volumes:
  payroll-keycloak:

