apiVersion: v1
kind: PersistentVolume
metadata:
  name: employee-service-db-pv
  labels:
    app: employee-service-db-pv
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOncePod
  hostPath:
    path: /data/employee-service-db
