apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-data-pv
  labels:
    app: grafana-data-pv
spec:
  storageClassName: ""
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOncePod
  hostPath:
    path: /data/grafana-data
