apiVersion: v1
kind: PersistentVolume
metadata:
  name: income-tax-service-db-pv
  labels:
    app: income-tax-service-db-pv
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOncePod
  hostPath:
    path: /data/income-tax-service-db
