apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-data-pv-0
  labels:
    app: kafka-data-pv-0
spec:
  storageClassName: "kafka"
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/kafka-data-0
