apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-data-pv-1
  labels:
    app: kafka-data-pv-1
spec:
  storageClassName: "kafka"
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/kafka-data-1
