apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-db-pv
  labels:
    app: keycloak-db-pv
spec:
  storageClassName: ""
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOncePod
  hostPath:
    path: /data/keycloak-db
