apiVersion: v1
kind: Service
metadata:
  name: keycloak-db
  labels:
    app: keycloak-db
spec:
  ports:
    - port: 5432
  clusterIP: None
  selector:
    app: keycloak-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak-db
spec:
  selector:
    matchLabels:
      app: keycloak-db
  serviceName: "keycloak-db"
  replicas: 1
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: keycloak-db
          image: postgres:17.0
          env:
            - name: POSTGRES_DB
              value: "keycloak_db"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-db
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db
                  key: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: "/var/lib/postgresql/data"

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOncePod" ]
        storageClassName: ""
        selector:
          matchLabels:
            app: keycloak-db-pv
        resources:
          requests:
            storage: 4Gi
