apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  ports:
    - port: 9090
  clusterIP: None
  selector:
    app: prometheus
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  serviceName: "prometheus"
  replicas: 1
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: prometheus
          image: prom/prometheus:v2.55.1
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: "/etc/prometheus"
            - name: data
              mountPath: "/prometheus"
      volumes:
        - name: config
          configMap:
            name: prometheus-configmap
            items:
              - key: "prometheus.yml"
                path: "prometheus.yml"

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOncePod" ]
        storageClassName: ""
        selector:
          matchLabels:
            app: prometheus-data-pv
        resources:
          requests:
            storage: 8Gi
