spring:
  application:
    name: income-tax-service
  datasource:
    url: jdbc:postgresql://localhost:5432/income_tax_db
    username: service
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

service:
  instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: 0 # random port

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env,caches,threaddump,logfile"

security:
  service:
    username: microservice
    password: password

eureka:
  instance:
    instanceId: ${service.instanceId}
  client:
    serviceUrl:
      defaultZone: http://${security.service.username}:${security.service.password}@localhost:8761/eureka/

springdoc:
  swagger-ui:
    path: /income/swagger-ui.html
  api-docs:
    path: /income/api-docs

#logging:
#  file:
#    name: ./logs/${spring.application.name}-log.log
