spring:
  application:
    name: payroll-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payroll_db
    username: service
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 0

service:
  instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

kafka:
  topicName: work-attendance-events
  trustedPackages:
    workAttendancePublishService: 'com.gabrielluciano.workattendancepublishservice.*'

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env,caches,threaddump,logfile"

security:
  service:
    username: microservice
    password: password

eureka:
  instance:
    instanceId: ${service.instanceId}
  client:
    serviceUrl:
      defaultZone: http://${security.service.username}:${security.service.password}@localhost:8761/eureka/

services:
  employeeServiceName: employee-service
  incomeTaxServiceName: income-tax-service
  inssTaxServiceName: inss-tax-service

springdoc:
  swagger-ui:
    path: /payrolls/swagger-ui.html
  api-docs:
    path: /payrolls/api-docs

#logging:
#  file:
#    name: ./logs/${spring.application.name}-log.log
