spring:
  application:
    name: payroll-service
  datasource:
    url: ${DATABASE_URL}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: ${SERVER_PORT}

service:
  instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

kafka:
  bootstrapServers: ${KAFKA_BOOTSTRAP_SERVERS}
  topicName: work-attendance-events
  trustedPackages:
    workAttendancePublishService: 'com.gabrielluciano.workattendancepublishservice.*'
  sasl:
    username: ${KAFKA_SASL_USERNAME}
    password: ${KAFKA_SASL_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env,caches,threaddump,logfile,prometheus"

eureka:
  client:
    enabled: false

services:
  employeeService:
    name: employee-service
    url: ${EMPLOYEE_SERVICE_URL}
  incomeTaxService:
    name: income-tax-service
    url: ${INCOME_TAX_SERVICE_URL}
  inssTaxService:
    name: inss-tax-service
    url: ${INSS_TAX_SERVICE_URL}

springdoc:
  swagger-ui:
    path: /payrolls/swagger-ui.html
  api-docs:
    path: /payrolls/api-docs

logging:
  file:
    name: ./logs/${spring.application.name}-log.log
