spring:
  application:
    name: payroll-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/payroll_db
    username: service
    password: password

service:
  instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

kafka:
  topicName: work-attendance-events
  trustedPackages:
    workAttendancePublishService: 'com.gabrielluciano.workattendancepublishservice.*'

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env,caches,threaddump,logfile"

eureka:
  instance:
    instanceId: ${service.instanceId}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#logging:
#  file:
#    name: ./logs/${spring.application.name}-log.log
