spring:
  application:
    name: payroll-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payroll_db
    username: service
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

service:
  instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

kafka:
  topicName: work-attendance-events
  trustedPackages:
    workAttendancePublishService: 'com.gabrielluciano.workattendancepublishservice.*'

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env,caches,threaddump,logfile"

eureka:
  instance:
    instanceId: ${service.instanceId}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

services:
  employeeServiceName: employee-service
  incomeTaxServiceName: income-tax-service

#logging:
#  file:
#    name: ./logs/${spring.application.name}-log.log
