spring:
  application:
    name: payroll-service
  datasource:
    url: ${DATABASE_URL}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 0

service:
  instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

kafka:
  bootstrapServers: ${KAFKA_BOOTSTRAP_SERVERS}
  topicName: work-attendance-events
  trustedPackages:
    workAttendancePublishService: 'com.gabrielluciano.workattendancepublishservice.*'

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env,caches,threaddump,logfile,prometheus"

security:
  username: ${EUREKA_SECURITY_USERNAME}
  password: ${EUREKA_SECURITY_PASSWORD}

eureka:
  instance:
    instanceId: ${service.instanceId}
  client:
    serviceUrl:
      defaultZone: http://${security.username}:${security.password}@${EUREKA_SERVER_HOST}:8761/eureka/

services:
  employeeService:
    name: employee-service
    url: ""
  incomeTaxService:
    name: income-tax-service
    url: ""
  inssTaxService:
    name: inss-tax-service
    url: ""

springdoc:
  swagger-ui:
    path: /payrolls/swagger-ui.html
  api-docs:
    path: /payrolls/api-docs

logging:
  file:
    name: ./logs/${spring.application.name}-log.log
